# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
- name: components.tokenizers.VietnameseTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: components.featurizers.FastTextFeaturizer
  cache_dir: .cache/fasttext
  file: cc.vi.300.bin
- name: DIETClassifier
  epochs: 50
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 2
    epochs: 100
    constrain_similarities: true
